services:
  edilflow:
    build:
      context: .
    volumes:
      - ./:/var/www/html
    # environment:
    #   - XDEBUG_MODE=${XDEBUG_MODE:-debug}
    #   - XDEBUG_IDEKEY=${XDEBUG_IDEKEY:-PHPSTORM}
    #   - XDEBUG_CLIENT_PORT=${XDEBUG_CLIENT_PORT:-9004}
    #   - XDEBUG_SESSION=1
    #   - PHP_IDE_CONFIG=serverName=edilflow-fullstack-test
    ports:
      - "8080:80"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
  mysql:
    image: mysql:lts
    volumes:
      - ./services/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "127.0.0.1:${MYSQL_PORT_MAP:-8306}:3306"
      - "3306"
  mailhog:
    image: mailhog/mailhog:latest
    platform: linux/amd64
    ports:
      - "1025:1025"  # Porta SMTP
      - "8025:8025"  # Porta per l'interfaccia web
    environment:
      - MH_STORAGE=maildir  # Opzionale: salva le email in formato maildir
    volumes:
      - mailhog-data:/maildir  # Opzionale: persistenza dei dati

volumes:
  mailhog-data:

networks:
    edilflow:
        driver: bridge

